// Generated by CoffeeScript 1.10.0
module.exports = function(mixedTranslations) {
  var traverse;
  traverse = function(obj, absKey, translations) {
    var i, key, len, ref, trans, value;
    if (absKey == null) {
      absKey = [];
    }
    if (translations == null) {
      translations = {};
    }
    for (key in obj) {
      value = obj[key];
      if ((value != null) && typeof value === "object") {
        traverse(value, absKey.concat(key), translations);
      } else {
        trans = translations;
        ref = [key].concat(absKey.slice(0, -1));
        for (i = 0, len = ref.length; i < len; i++) {
          key = ref[i];
          trans = trans[key] != null ? trans[key] : trans[key] = {};
        }
        trans[absKey[absKey.length - 1]] = value;
      }
    }
    return translations;
  };
  return traverse(mixedTranslations);
};
